### ISSUE TITLE
Export header as include/nlhoman/json.hpp

### ISSUE THREAD

**Issue by Manu343726** [arnemertz/conan-nlJson#2]
Hi Arne,

I'm working on migrating all siplasplas dependencies to conan and I've picked your package for the JSON For Modern C++ dependency. It works like a charm, but I noticed the package exports the library as `include/json.hpp`, with my include directives being `#include <json.hpp>`

I usually like to have all includes qualified so I know where the headers are coming from, also solving potential ambiguity issues.

What do you think about packaging the library as `include/nlhoman/json.hpp` (Or something similar) ?

Anyway, thanks for packaging this great lib for me ;)

**Comment by arnemertz** [comment]
Hi Manu,

I agree, good idea. I am somewhat hesitant to break stuff in the middle of no particular Release, but I should be able to find out how to make the export path configurable.

Cheers, Arne

**Comment by arnemertz** [comment]
Hi again,
you should now be able to specify `nlJson:path=nlohmann` in the options section of your _conanfile.txt_ to have it packaged as `include/nlohmann/json.hpp`.
