### ISSUE TITLE
Rename library to "nlohmann/json" or similar

### ISSUE THREAD

**Issue by nlohmann** [arnemertz/conan-nlJson#3]
I understand the name "JSON for Modern C++" is not as sticky as I hoped it would be :-) But in Reddit/StackOverflow, people use "nlohmann/json" or similar to identify the library. I fear that using "nlJson" for Conan could even add to the confusion.

Is it possible to rename this?

**Comment by arnemertz** [comment]
I am not sure if Conan can deal with slashes - in fact I doubt it. I'll have a look at a better name.

**Comment by nlohmann** [comment]
How about `nlohmann_json` as it is used by vcpkg?

**Comment by arnemertz** [comment]
I haven't updated this repo for an eternity - obviously. isn't there a more official conan package that is maintained?

**Comment by arnemertz** [comment]
Found this: https://github.com/vthiery/conan-jsonformoderncpp
I'll close this repo in favor of that one.
